language: python
cache:
  pip: true
  directories:
    - /home/travis/.rvm/gems

git:
  depth: 2
jobs:
  allow_failures:
    env:
      - CAN_FAIL=true

  include:
    - stage: cache-and-validate
      name: "Create install cache and validate updated assemblies"
      install:
        - gem install asciidoctor asciidoctor-diagram rouge
        - pip3 install pyyaml aura.tar.gz
      script:
        # Fail if Asciidoctor encounters errors. Run only if there are modified AsciiDoc files
        - if ! [[ -z $(git diff --name-only HEAD~1 HEAD --diff-filter=d '*.adoc' ':(exclude)_unused_topics/*') ]]; then chmod +x ./scripts/check-asciidoctor-build.sh && ./scripts/check-asciidoctor-build.sh; fi

    - stage: build
      name: "Build openshift-gitops distro"
      script:
        - python3 build.py --distro openshift-gitops --product "OpenShift GitOps" --version 1.9 --no-upstream-fetch && python3 makeBuild.py

    - stage: netlify
      name: "Build and deploy with Netlify"
      env:
        - CAN_FAIL=true
      language: minimal
      if: type IN (pull_request) AND branch IN (gitops-docs, gitops-docs-1.8, gitops-docs-1.9, gitops-docs-1.10) AND sender != "openshift-cherrypick-robot"
      script:
        - chmod +x autopreview.sh
        - ./autopreview.sh

stages:
  - cache-and-validate
  - build
  - netlify
