language: python
cache: pip
# env:
#   - PR_AUTHOR=${TRAVIS_PULL_REQUEST_SLUG::-15}
git:
  depth: 2
jobs:
  allow_failures:
    env:
      - CAN_FAIL=true
  include:
    # fail if asciidoctor encounters errors
    - stage: validate
      name: "Validate updated assemblies with Asciidoctor"
      install:
        - gem install asciidoctor
        - gem install asciidoctor-diagram
        - gem install rouge
      script:
        - chmod +x ./scripts/check-asciidoctor-build.sh
        - ./scripts/check-asciidoctor-build.sh
    - stage: build
      name: "Build openshift-gitops distro"
      before_install:
        - gem install asciidoctor
        - gem install asciidoctor-diagram
      install:
        - pip3 install pyyaml
        - pip3 install aura.tar.gz
      script:
        - python3 build.py --distro openshift-gitops --product "OpenShift GitOps" --version 1.9 --no-upstream-fetch && python3 makeBuild.py

    # Remove Vale stage until PR commenting feature is ready
    # - stage: check-with-vale
    #   env:
    #     - CAN_FAIL=true
    #   if: type IN (pull_request) AND sender != "openshift-cherrypick-robot"
    #   name: "Run Vale against PR asciidoc files"
    #   language: minimal
    #   before_script:
    #     - gem install asciidoctor
    #   script:
    #     - travis_retry wget https://github.com/errata-ai/vale/releases/download/v2.15.4/vale_2.15.4_Linux_64-bit.tar.gz --retry-connrefused
    #     - mkdir bin && tar -xvzf vale_2.15.4_Linux_64-bit.tar.gz -C bin
    #     - export PATH=./bin:"$PATH"
    #     - travis_retry vale sync # pull down VRH rules package
    #     - chmod +x ./scripts/check-with-vale.sh
    #     - ./scripts/check-with-vale.sh
    # Commenting out to disable auto-merging of PRs
    # - stage: automerge
    #   if: env(PR_AUTHOR)=openshift-cherrypick-robot
    #   script: bash ./automerge.sh
    - stage: netlify
      env:
        - CAN_FAIL=true
      language: minimal
      if: type IN (pull_request) AND branch IN (gitops-docs, gitops-docs-1.8, gitops-docs-1.9) AND sender != "openshift-cherrypick-robot"
      script:
        - chmod +x autopreview.sh && ./autopreview.sh

stages:
  - validate
  - build
  - netlify
  #- check-with-vale
  #- automerge
